### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by adink1** [azerothcore/mod-pvp-zones#9]
/home/ubuntu/azerothcore/modules/mod-pvp-zones/src/ZoneScript.cpp:40:40: fatal e                                                                                                                                                             rror: no member named 'GetGameTime' in 'IWorld'
    time_t last_announcement = sWorld->GetGameTime();
                               ~~~~~~  ^
1 error generated.

**Comment by 55Honey** [comment]
Hi @adink1,
I think this module is still work-in-progress.
It can't do anything yet. Feel free to help finishing it. There are open issues with info, what is left to do.

**Comment by iraizo** [comment]
I cannot reproduce this/work on this right now due to missing support of arm64 and missing support of windows.

And yes this is unfinished, 2 things still need to get sorted and testing needs to be done
